CMS.Presentation/Controllers/TemplateController.cs
using System;
using System.Net;
using System.Web.Mvc;
using CMS.Application.ViewModels;
using CMS.Application;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Linq;
using CMS.Application.Application;

namespace CMS.Presentation.Controllers
{
    public class TemplateController : Controller
    {
        private IMenuAppService _menuAppService;
        private IMenuInRoleAppService _menuInRolesAppService;
        private readonly ApplicationUserManager userManager;
        private readonly ApplicationRoleManager roleManager;
        public TemplateController(ApplicationUserManager userManager, ApplicationRoleManager roleManager,
            IMenuAppService menuAppService, IMenuInRoleAppService menuInRolesAppService)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            _menuInRolesAppService = menuInRolesAppService;
            _menuAppService = menuAppService;
        }
        public PartialViewResult Header()
        {
            return PartialView();
        }
        public PartialViewResult Sidebar()
        {

            var lsCurrentRole = new List<string>();
            //Da login => lay list role
            if (User.Identity.IsAuthenticated)
            {
                var currentRole = CurrentRole();
                foreach (var name in currentRole)
                {
                    lsCurrentRole.Add(roleManager.FindByNameAsync(name).Result.Id);
                }
                string userId = User.Identity.GetUserId();
                var Name = userManager.Users.FirstOrDefault(c => c.Id == userId).Name;
                ViewBag.Name = Name;
            }
            //chua login/ thi lay role la anomymous
            else
            {
                return PartialView(new List<MenuViewModel>());
                //lsCurrentRole.Add(roleManager.FindByNameAsync("Anonymous").Result.Id);
            }
            //get current menu tu role
            var lsCurrentMenu = _menuInRolesAppService.GetAll().Where(c => lsCurrentRole.Contains(c.RoleId.ToString())).Select(c => c.MenuId);

            var model = _menuAppService.GetParent()
                .Where(c => lsCurrentMenu.Contains(c.Id))
                .OrderBy(c => c.Order)
                .Select(l => new MenuViewModel
                {
                    Id = l.Id,
                    Name = l.Name,
                    Url = l.Url,
                    Icon = l.Icon,
                    Order = l.Order,
                    IsActive = l.IsActive,
                    ParentId = l.ParentId,
                    Childrens = GetChildren(l.Id)
                });
            return PartialView(model);
        }
        public PartialViewResult Footer()
        {
            return PartialView();
        }

        private List<MenuViewModel> GetChildren(int parentId)
        {
            var lsCurrentRole = new List<string>();
            //Da login => lay list role
            if (User.Identity.IsAuthenticated)
            {
                var currentRole = CurrentRole();
                foreach (var name in currentRole)
                {
                    lsCurrentRole.Add(roleManager.FindByNameAsync(name).Result.Id);
                }
            }
            //chua login/ thi lay role la anomymous
            else
            {
                lsCurrentRole = new List<string>();
                //lsCurrentRole.Add(roleManager.FindByNameAsync("Anonymous").Result.Id);
            }
            //get current menu tu role
            var lsCurrentMenu = _menuInRolesAppService.GetAll().Where(c => lsCurrentRole.Contains(c.RoleId.ToString())).Select(c => c.MenuId);

            return _menuAppService.GetChildren(parentId)
                 .Where(c => lsCurrentMenu.Contains(c.Id))
                 .OrderBy(l => l.Order)
                .Select(l => new MenuViewModel
                {
                    Id = l.Id,
                    Name = l.Name,
                    Url = l.Url,
                    Icon = l.Icon,
                    Order = l.Order,
                    IsActive = l.IsActive,
                    ParentId = l.ParentId,
                    Childrens = GetChildren(l.Id)
                }).ToList();
        }
        private List<string> CurrentRole()
        {
            var UserId = HttpContext.User.Identity.GetUserId();
            var currentRole = userManager.GetRoles(UserId);
            return currentRole.ToList();
        }


    }
}

CMS.Presentation/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Content/bower_components/Ionicons/css/ionicons.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <!-- bootstrap datepicker -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/Content/plugins/iCheck/all.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="~/Content/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css">
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet" href="~/Content/plugins/timepicker/bootstrap-timepicker.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/Content/bower_components/select2/dist/css/select2.min.css">
    <link href="~/Content/bower_components/toastr/toastr.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="~/Content/dist/css/skins/_all-skins.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body ng-app="MyApp" class="hold-transition skin-black sidebar-mini">
    <div ng-controller="MasterPageController" ng-cloak>
        <div id="cover-spin" ng-show="MasterPage.IsLoading"></div>
    </div>
    <div class="wrapper">
        @Html.Action("Header", "Template", new { Area = "" })
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Action("Sidebar", "Template", new { Area = "" })
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @*<div style="padding: 20px 30px; background: rgb(243, 156, 18); z-index: 999999; font-size: 16px; font-weight: 600;">
            <a href="https://themequarry.com" style="color: rgba(255, 255, 255, 0.9); display: inline-block; margin-right: 10px; text-decoration: none;">
                Ready to sell your theme? Submit your theme to our new marketplace now and let over 200k visitors see it!</a>
                <a class="btn btn-default btn-sm" href="https://themequarry.com" style="margin-top: -5px; border: 0px; box-shadow: none; color: rgb(243, 156, 18); font-weight: 600; background: rgb(255, 255, 255);">Let's Do It!
                </a>
            </div>*@

            <!-- Main content -->
            <section class="content">
                <div class="row">
                    @RenderBody()
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        @Html.Action("Footer", "Template", new { Area = "" })
        <!-- Add the sidebar's background. This div must be placed
        immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/Content/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Content/bower_components/lodash/core.js"></script>
    <script src="~/Content/bower_components/toastr/toastr.min.js"></script>

    <!-- Select2 -->
    <script src="~/Content/bower_components/select2/dist/js/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="~/Content/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/Content/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="~/Content/plugins/input-mask/jquery.inputmask.extensions.js"></script>
    <!-- date-range-picker -->
    <script src="~/Content/bower_components/moment/min/moment.min.js"></script>
    <script src="~/Content/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap datepicker -->
    <script src="~/Content/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!-- bootstrap color picker -->
    <script src="~/Content/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
    <!-- bootstrap time picker -->
    <script src="~/Content/plugins/timepicker/bootstrap-timepicker.min.js"></script>
    <!-- SlimScroll -->
    <script src="~/Content/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <!-- iCheck 1.0.1 -->
    <script src="~/Content/plugins/iCheck/icheck.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- DataTables -->
    <script src="~/Content/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/bower_components/sweetalert/sweetalert.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
    <!-- Page script -->
    <script>
        $(function () {
                $("a[title='BotDetect CAPTCHA ASP.NET Form Validation']").remove();

            //Initialize Select2 Elements
            $('.select2').select2();
            //Date picker
            $('#datepicker').datepicker({
                autoclose: true
            });
        $('[data-mask]').inputmask();
        });
    </script>
    <script src="~/Content/assets/angular-1.6.3/angular.min.js"></script>
    <script src="~/Content/assets/angular-1.6.3/angular-route.min.js"></script>
    <script src="~/Content/assets/app/app-bundle.js"></script>
    <script src="~/Content/dist/js/site.js"></script>

    @if (User.Identity.IsAuthenticated)
    {
        HttpCookie userCookie = new HttpCookie("userid");
        userCookie.Value = User.Identity.GetUserId();
        userCookie.Expires = DateTime.Now.AddYears(100);
        //userCookie.Path = "/Redirect";
        Response.SetCookie(userCookie);
    }
    @RenderSection("scripts", required: false)
</body>
</html>